# Generated by Django 3.2.16 on 2022-12-06 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0002_auto_20221206_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='defaultcomission',
            options={'verbose_name': 'Comissão Padrão', 'verbose_name_plural': 'Comissões Padrões'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item da Venda', 'verbose_name_plural': 'Itens da(s) Venda(s)'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 19, 20, 44, 772200), verbose_name='Data e Hora da Venda'),
        ),
    ]
