# Generated by Django 3.2.16 on 2022-12-06 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0003_auto_20221206_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='telefone',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 20, 0, 59, 33205), verbose_name='Data e Hora da Venda'),
        ),
    ]
