# Generated by Django 3.2.16 on 2022-12-06 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0004_auto_20221206_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='telefone',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 20, 15, 43, 824026), verbose_name='Data e Hora da Venda'),
        ),
    ]
