# Generated by Django 3.2.16 on 2022-12-07 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0005_auto_20221206_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultcomission',
            name='day',
            field=models.IntegerField(choices=[(1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday'), (7, 'Monday')], primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 21, 3, 42, 304691), verbose_name='Data e Hora da Venda'),
        ),
    ]
