# Generated by Django 3.2.16 on 2022-12-07 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0006_auto_20221206_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultcomission',
            name='name',
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 21, 11, 43, 37896), verbose_name='Data e Hora da Venda'),
        ),
    ]
