# Generated by Django 3.2.16 on 2022-12-07 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0009_auto_20221206_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em (UTC)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em (UTC)'),
        ),
        migrations.AlterField(
            model_name='defaultcomission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em (UTC)'),
        ),
        migrations.AlterField(
            model_name='defaultcomission',
            name='day',
            field=models.IntegerField(choices=[(1, 'Segunda-Feira'), (2, 'Terça-Feira'), (3, 'Quarta-Feira'), (4, 'Quinta-Feira'), (5, 'Sexta-Feira'), (6, 'Sábado'), (7, 'Domingo')], primary_key=True, serialize=False, verbose_name='Dia da semana'),
        ),
        migrations.AlterField(
            model_name='defaultcomission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em (UTC)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em (UTC)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em (UTC)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em (UTC)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em (UTC)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em (UTC)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 21, 36, 51, 880291), verbose_name='Data e Hora da Venda'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em (UTC)'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em (UTC)'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em (UTC)'),
        ),
    ]
