# Generated by Django 3.2.16 on 2022-12-07 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0011_auto_20221206_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 7, 56, 34, 178344), verbose_name='Data e Hora da Venda'),
        ),
    ]
