# Generated by Django 3.2.16 on 2022-12-07 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0012_alter_sale_sale_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultcomission',
            options={'ordering': ['day'], 'verbose_name': 'Comissão Padrão', 'verbose_name_plural': 'Comissões Padrões'},
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 8, 2, 16, 626928), verbose_name='Data e Hora da Venda'),
        ),
    ]
