# Generated by Django 3.2.16 on 2022-12-07 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0015_auto_20221207_0814'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultComission',
            new_name='DefaultCommission',
        ),
        migrations.RenameField(
            model_name='defaultcommission',
            old_name='max_comission',
            new_name='max_commission',
        ),
        migrations.RenameField(
            model_name='defaultcommission',
            old_name='min_comission',
            new_name='min_commission',
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 8, 18, 9, 193174), verbose_name='Data e Hora da Venda'),
        ),
    ]
