# Generated by Django 3.2.16 on 2022-12-07 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0016_auto_20221207_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 11, 34, 27, 810396), verbose_name='Data e Hora da Venda'),
        ),
        migrations.AddConstraint(
            model_name='defaultcommission',
            constraint=models.CheckConstraint(check=models.Q(('min_commission__gte', 0), ('min_commission__lte', 10)), name='Valor deve ser estar entre 0 e 1'),
        ),
    ]
