# Generated by Django 3.2.16 on 2022-12-07 14:48

import datetime
from decimal import Decimal
from django.db import migrations, models
import stationery.models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0019_auto_20221207_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultcommission',
            options={'ordering': ['day'], 'verbose_name': 'Comissão Padrão', 'verbose_name_plural': 'Comissões Padrões'},
        ),
        migrations.AlterField(
            model_name='defaultcommission',
            name='max_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=4, validators=[stationery.models.DefaultCommission.range_commision], verbose_name='Comissão máxima'),
        ),
        migrations.AlterField(
            model_name='defaultcommission',
            name='min_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, validators=[stationery.models.DefaultCommission.range_commision], verbose_name='Comissão mínima'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 11, 48, 49, 60961), verbose_name='Data e Hora da Venda'),
        ),
    ]
