# Generated by Django 3.2.16 on 2022-12-07 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0021_alter_sale_sale_datetime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='ItemSale',
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 11, 56, 52, 751082), verbose_name='Data e Hora da Venda'),
        ),
    ]
