# Generated by Django 3.2.16 on 2022-12-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0025_alter_sale_sale_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='commission',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Percentual de comissão'),
        ),
    ]
