# Generated by Django 3.2.16 on 2022-12-08 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0029_auto_20221208_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsale',
            options={'verbose_name': 'Item da Venda', 'verbose_name_plural': 'Itens de Vendas'},
        ),
    ]
